### ISSUE TITLE
mgt-get-multiple-person - How to limit the persona data to people only and not support or conference room?

### ISSUE THREAD

**Issue by gretchunkim** [pnp/mgt-samples#5]
![Capture](https://user-images.githubusercontent.com/8564035/162988040-db89997a-6dd2-4f34-b5d5-63997214eb5a.PNG)
### Sample

mgt-get-multiple-person

### Author(s)

@aaclage 

### Question

What will be your strategy to filter non-person data (Support, Conference Room, etc.)?
Thank you!

**Comment by sebastienlevert** [comment]
These conference rooms in the demo tenant we are using are "users". In a real-world scenario, these conference rooms should be resources and would not show up in the results. This is really just because of the demo tenant that the sample is using! Thanks for the question!

I'll close the issue for now but feel free to reopen!
